spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S09P12D102
    username: S09P12D102@stg-yswa-kr-practice-db-master.mariadb.database.azure.com
    password: 11jBMoEHvm
#    url: jdbc:mysql://127.0.0.1:3306/S09P12D102
#    username: root
#    password: ssafy
    hikari:
      maximumpoolsize: 150
      connectionTimeout : 30000
      maxLifetime : 1800000
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: update # 운영시에는 validate 추천
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
